name: event-reliability

addons:
- name: metron_agent
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: metron_agent
    release: loggregator
    consumes:
      doppler: {deployment: cf, from: doppler}
    properties:
      metron_agent:
        bosh_dns: true
      loggregator:
        tls:
          ca_cert: "((loggregator_tls_metron.ca))"
          metron:
            cert: "((loggregator_tls_metron.certificate))"
            key: "((loggregator_tls_metron.private_key))"
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns

instance_groups:
- name: event_emitter
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: event_emitter
    release: loggregator-capacity-planning
    properties:
      host: "((system_domain))"
      datadog:
        api_key: "((datadog_key))"
      tls:
        ca: "((event_emitter.ca))"
        cert: "((event_emitter.certificate))"
        key: "((event_emitter.private_key))"
  - name: v2_event_counter
    release: loggregator-capacity-planning
    consumes:
      reverse_log_proxy: {deployment: cf, from: reverse_log_proxy}
    properties:
      tls:
        ca: "((event_counter.ca))"
        cert: "((event_counter.certificate))"
        key: "((event_counter.private_key))"

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: loggregator-capacity-planning
  version: latest
- name: loggregator
  version: latest
- name: bosh-dns
  sha1: 9231b7c7d2f6aa85e0cb77fdeef7add54fdb3f1a
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.2.0
  version: 0.2.0

variables:
- name: loggregator_ca
  type: certificate
  options:
    is_ca: true
    common_name: CA
- name: event_emitter
  type: certificate
  options:
    ca: loggregator_ca
    common_name: event_emitter
    extended_key_usage:
    - client_auth
    - server_auth
- name: event_counter
  type: certificate
  options:
    ca: loggregator_ca
    common_name: event_counter
    extended_key_usage:
    - client_auth
    - server_auth
- name: loggregator_tls_metron
  type: certificate
  options:
    ca: loggregator_ca
    common_name: metron
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
